### ISSUE TITLE
Add Dutch language as PoC of multilingual interface

### ISSUE THREAD

**Issue by GertjanFi** [colonial-heritage/dataset-browser#60]

**Comment by barbarah** [comment]
There is a bug in the translation plugin we are using (next-intl), that prevents us from correctly translating the labels in de client-side dataset list. 

We are using a beta version of next-intl because we are using the [app Directory (beta)](https://nextjs.org/blog/next-13#new-app-directory-beta) of nextjs. This is not working perfectly. But next-intl is releasing new versions very quickly (releases every couple of days). We decided to wait a week or two. The fix we are waiting for: https://github.com/amannn/next-intl/pull/184

The alternative is moving to i18next. But i18next also doesn't integrate perfectly with the beta app directory.

I would like to have a working version before the next workshop day (24 Feb). So we probably can wait until 17 Feb.
